CREATE TABLE SITES (ID BIGINT AUTO_INCREMENT PRIMARY KEY,  NAME CHAR(255), EMAIL VARCHAR(500), CONTACT BIGINT, COUNTRY CHAR(255), STATE CHAR(255), CITY CHAR(255), LANDMARK VARCHAR(500), PINCODE BIGINT, LANDTYPE CHAR(100));
CREATE TABLE OTPS (EMAIL VARCHAR(500) PRIMARY KEY, OTP BIGINT, TIME_STAMP VARCHAR(500));
CREATE TABLE USERS (NAME VARCHAR(100), EMAIL VARCHAR(500) PRIMARY KEY, CONTACT BIGINT, PASSWORD VARCHAR(500));
